version: '2'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname:  rabbitmq
    restart: always
    #此环境变量设置rabbitmq 的初始 用户，密码，和vhost，并且删除了默认的guest用户
    #此变量与spring－service中的变量设置一致，一同修改
    environment:
      RABBITMQ_DEFAULT_USER: wfij
      RABBITMQ_DEFAULT_PASS: kkslcm8923s
      RABBITMQ_DEFAULT_VHOST: /wfij
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - wfij

 

  confirm-rabbit:
    image: confirm-rabbit:0.0.1-SNAPSHOT
    container_name: confirm-rabbit
    restart: always
    environment:
      RABBIT_HOST: rabbitmq
    ports:
      - "8080:8080"
    networks:
      - wfij
    depends_on:
      - rabbitmq

  fanout-rabbit:
    image: confirm-rabbit:0.0.1-SNAPSHOT
    container_name: fanout-rabbit
    restart: always
    environment:
      RABBIT_HOST: rabbitmq
    ports:
      - "8081:8081"
    networks:
      - wfij
    depends_on:
      - rabbitmq
      
  fixed-reply:
    image: fixed-reply:0.0.1-SNAPSHOT
    container_name: fixed-reply
    restart: always
    environment:
      RABBIT_HOST: rabbitmq
    ports:
      - "8082:8082"
    networks:
      - wfij
    depends_on:
      - rabbitmq
   
  topic-rabbit:
    image: topic-rabbit:0.0.1-SNAPSHOT
    container_name: topic-rabbit
    restart: always
    environment:
      RABBIT_HOST: rabbitmq
    ports:
      - "8083:8083"
    networks:
      - wfij
    depends_on:
      - rabbitmq



networks:
  wfij:
    external:
      name: wfij-net





